---
- name: "Debian : uninstall distro packages"
  ansible.builtin.package:
    state: absent
    name:
      - containerd
      - docker-compose
      - docker-doc
      - docker.io
      - podman-docker
      - runc

- name: "Debian : install requirements"
  ansible.builtin.package:
    name:
      - curl
      - python3-pexpect

- name: "Debian : make sure /etc/apt/keyrings/ is there"
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory

- name: "Debian : install docker repository key"
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker-ce.gpg
    executable: /bin/bash
  args:
    creates: /etc/apt/keyrings/docker-ce.gpg
  register: _gpg_key

- name: "Debian : install docker repository"
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker-ce.list
    content: "{{ docker_ce_sources_list }}"
    mode: "0644"
    owner: root
    group: root
  register: _repository

- name: "Debian : apt-get update"
  ansible.builtin.command: apt-get update
  when: _gpg_key.changed or _repository.changed
  changed_when: false
