---
- name: Uninstall distro packages
  ansible.builtin.package:
    state: absent
    name:
      - containerd
      - docker-compose
      - docker-doc
      - docker.io
      - podman-docker
      - runc

- name: Install requirements
  ansible.builtin.package:
    name:
      - curl
      - python3-pexpect

- name: Make sure /etc/apt/keyrings/ is there
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory

- name: Delete repository key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker-ce.gpg
    state: absent
  when: reinstall_repository_key is defined and reinstall_repository_key

- name: Install docker repository key (-e reinstall_repository_key=true)
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -fsSL {{ docker_ce_reposity_key_url }} | gpg --dearmor -o /etc/apt/keyrings/docker-ce.gpg
    executable: /bin/bash
  args:
    creates: /etc/apt/keyrings/docker-ce.gpg
  register: _gpg_key

- name: Install docker repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker-ce.list
    content: "{{ docker_ce_sources_list }}"
    mode: "0644"
    owner: root
    group: root
  register: _repository

- name: Apt update
  ansible.builtin.command: apt-get update
  when: _gpg_key.changed or _repository.changed
  changed_when: false
