---
- name: Import tasks for {{ ansible_distribution }}
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
- name: Import tasks for docker ce
  ansible.builtin.import_tasks: docker-ce.yml
- name: Import setup tasks
  ansible.builtin.import_tasks: setup.yml
- name: Import tasks for rootless setup
  ansible.builtin.import_tasks: rootless.yml
