---
# non-root user running the containers
# generate a hash using 'openssl passwd -6' for a SHA512.
# docker_rootless_user:
#   name: dockuser
#   home: /opt/dockuser
#   shell: /usr/bin/bash
#   uid: 2222
#   pw: < password for reference only, not required by the role >
#   pwhash: < the password hash used by ansible.builtin.user >
#   authorized_keys: |
#     pubkey1 set SSH authorized keys
#     pubkey2 for this account
