---
# non-root user running the containers
# generate a hash using 'openssl passwd -6' for a SHA512.
# docker_rootless_user:
#   name: dockuser
#   home: /opt/dockuser
#   shell: /usr/bin/bash
#   uid: 2222
#   pwhash: < the password hash >
#   authorized_keys: |
#     pubkey1  add the SSH keys authorized
#     pubkey2  to access this account
