---
docker_ce_sources_list: "deb [signed-by=/etc/apt/keyrings/docker-ce.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

# cgroup v2 is enabled by default, set this to false to force cgroup v1.
docker_rootless_cgroupv2: true

# delete docker0 network interface on the host
docker_rootless_delete_docker0_network_interface: true

# authorize the role to restart the host
docker_rootless_reboot: false

# capabilities on rootlesskit
docker_rootless_capabilities:
  # Exposing privileged ports
  - cap: cap_net_bind_service=ep
    state: present

  # Limiting resources
  - cap: cap_sys_resource=ep
    state: present

# Limiting resources with systemd as Cgroup Driver
# https://docs.docker.com/engine/security/rootless/#limiting-resources
docker_rootless_systemd_delegate_conf: |
  [Service]
  Delegate=cpu cpuset io memory pids

# This must be “true” with Debian 11
docker_rootless_modprobe_iptables: false
