---
# cgroup v2 is enabled by default, set this to false to force cgroup v1.
docker_rootless_cgroupv2: true

# authorize the role to restart the host
docker_rootless_reboot: false

# capabilities on rootlesskit
docker_rootless_capabilities:
  - cap_net_bind_service=ep # Exposing privileged ports
  - cap_sys_resource=ep # Limiting resources

# Limiting resources with systemd as Cgroup Driver
# https://docs.docker.com/engine/security/rootless/#limiting-resources
docker_rootless_systemd_delegate_conf: |
  [Service]
  Delegate=cpu cpuset io memory pids

# This must be “true” with Debian 11
docker_rootless_modprobe_iptables: false
